# Generated by Django 5.1.2 on 2024-10-20 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicbackground",
            name="personal_info",
        ),
        migrations.RemoveField(
            model_name="professionalexperience",
            name="personal_info",
        ),
        migrations.AddField(
            model_name="academicbackground",
            name="contact_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_backgrounds",
                to="candidates.contactinfo",
            ),
        ),
        migrations.AddField(
            model_name="professionalexperience",
            name="contact_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professional_experiences",
                to="candidates.contactinfo",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="contact_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_info",
                to="candidates.contactinfo",
            ),
        ),
    ]
