# Generated by Django 5.1.2 on 2024-10-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "candidates",
            "0003_rename_end_date_academicbackground_acad_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
