version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/api
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"