services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"